name: Build Executable

on: [push, pull_request]

jobs:
  pyinstaller-build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pyinstaller
        run: |
          python -m pip install --upgrade pip
          $Env:PYINSTALLER_COMPILE_BOOTLOADER = "true"
          pip install --user --force-reinstall --ignore-installed --no-binary :all: pyinstaller
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create Executable for AIGUI
        run: |
          pyinstaller .\src\AIGUI.py -y --onedir --clean --noconsole --add-data .\screen\EDAI_logo.png;.\screen

      - name: Create Executable for Chat
        run: |
          pyinstaller .\src\Chat.py -y --onedir --clean --console --hidden-import=comtypes.stream --add-data $env:APPDATA\Python\Python38\site-packages\pysilero_vad\models\silero_vad.onnx;.\pysilero_vad\models --add-binary $env:APPDATA\Python\Python38\site-packages\onnxruntime\capi\onnxruntime_providers_shared.dll;.

      - name: Get current commit ID
        id: get_commit
        run: echo "::set-output name=commit_id::$(git rev-parse HEAD)"

      - name: Create start.bat script
        run: |
          $commitId = '${{ steps.get_commit.outputs.commit_id }}'
          $start = "@echo off`nstart \"\" .\AIGUI\AIGUI.exe --chat=Chat\Chat.exe --release=$commitId`nexit"
          $start | Out-File -Encoding ASCII .\dist\start.bat

      - name: Create zip file
        run: |
          Compress-Archive -Path .\dist\* -DestinationPath .\dist\build.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./dist/build.zip